services:
  app1:
    build:
      context: ./backend
    container_name: app1
    environment:
      - PORT=3001
    expose:
      - '3001'
    networks:
      - app-network

  app2:
    build:
      context: ./backend
    container_name: app2
    environment:
      - PORT=3002
    expose:
      - '3002'
    networks:
      - app-network

  app3:
    build:
      context: ./backend
    container_name: app3
    environment:
      - PORT=3003
    expose:
      - '3003'
    networks:
      - app-network

  app4:
    build:
      context: ./backend
    container_name: app4
    environment:
      - PORT=3004
    expose:
      - '3004'
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - app1
      - app2
      - app3
      - app4
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
