FROM nginx:latest

#Copy your nginx.conf from the nginx folder
COPY nginx/nginxlb.conf /etc/nginx/nginx.conf

# Copy built Angular files from dist folder
#COPY angularapp/dist/angularapp/browser /usr/share/nginx/html
